### ISSUE TITLE
Add support for marking AWS roles and policies as unused instead of deleting them upon cleanup

### ISSUE THREAD

**Issue by orishoshan** [otterize/credentials-operator#112]
Users have requested to be able to configure the credentials operator to not delete AWS IAM roles and policies, but instead tag them as unused, a sort of "soft delete" mode.

@omris94 please add info on how this feature will be configured

https://github.com/otterize/intents-operator/issues/366

**Comment by omris94** [comment]
I suggest the following solution: 

_To indicate that AWS IAM roles and policies should only be soft deleted when they are not used anymore, there are two methods to follow:_

1. If you want to avoid deletion of AWS roles and policies corresponding with a specific pod, label the pod as `credentials-operator.otterize.com/aws-use-soft-delete=true`.

2. If you want to globally avoid the deletion of AWS roles and policies, initialize the `credentials-operator` with the `--aws-use-soft-delete=true` flag. You can set this flag by adjusting the helm chart's value (`global.aws.useSoftDelete`).

_How would the soft deletion of AWS IAM roles and policies look like?_

- **Soft deletion of an AWS IAM policy** will be performed by tagging a policy as `otterize/softDeletedAt=<timeOfDeletion>`
- **Soft deletion of an AWS IAM role** will be performed by tagging a role and all of its policies as `otterize/softDeletedAt=<timeOfDeletion>`


When does the soft deletion occur?

- Every case that would cause a deletion without this feature, such as serviceAccount deletion for roles or ClientIntent deletion for policies.

**Comment by omris94** [comment]
At the moment, we don't have the necessary logic to remove orphaned policies/roles. This means that if you start with `--aws-use-soft-delete=true` or its pod-level equivalent, you will need to switch it back to `false` before deleting the pod or ClientIntents to ensure that the roles/policies are removed. However, everything is possible so we may be able to implement this logic in the future.

**Comment by volk1234** [comment]
So the answer is yes. Means that if I switch back operator will start manage role/policy. Looks good then.
